#!/bin/sh
set -eu

repo="${1:-.}"
out_dir="${2:?missing output directory}"
out_file="$out_dir/KKGeneratedBuildInfo.swift"

mkdir -p "$out_dir"

revision_count="$(git -C "$repo" rev-list --count HEAD 2>/dev/null || printf 'REV ?')"
revision_hash="$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || printf 'NO GIT')"
dirty_suffix=""

if ! git -C "$repo" diff --quiet HEAD -- 2>/dev/null; then
    dirty_suffix="+"
fi

cat > "$out_file" <<EOF
// Generated by Scripts/generate-build-info.sh. Do not edit.
enum KKGeneratedBuildInfo {
    static let revisionCount = "$revision_count$dirty_suffix"
    static let revisionHash = "$revision_hash"
}
EOF
